var playersData = [
  {
    id: 1,
    name: "Shakib Al Hasan",
    img: "http://t3.gstatic.com/licensed-image?q=tbn:ANd9GcSnn27coD_1wIFzntVYPE0JLeC3nuRD0TBfat56lur6gQbHFdUo0iqfQUj6sUHv",
    salary: 10000,
    battingStyle: " Left-handed",
    currentTeam: "Khulna Tigers",
    username: "Bret",
    email: "Sincere@april.biz",
    address: {
      street: "Kulas Light",
      suite: "Apt. 556",
      city: "Gwenborough",
      zipcode: "92998-3874",
      geo: {
        lat: "-37.3159",
        lng: "81.1496",
      },
    },
    phone: "1-770-736-8031 x56442",
    website: "hildegard.org",
    company: {
      name: "Romaguera-Crona",
      catchPhrase: "Multi-layered client-server neural-net",
      bs: "harness real-time e-markets",
    },
  },
  {
    id: 2,
    name: "Tamim Iqbal",
    img: "http://t3.gstatic.com/licensed-image?q=tbn:ANd9GcSptPOG9vT1rhY4hE4QQuDstM8u-AUNF_E6ZMYjkh00U9BUs18fpLVcCjbOFVpY",
    salary: 8000,
    battingStyle: " Left-handed",
    currentTeam: "Nagar Hurricane",
    username: "Antonette",
    email: "Shanna@melissa.tv",
    address: {
      street: "Victor Plains",
      suite: "Suite 879",
      city: "Wisokyburgh",
      zipcode: "90566-7771",
      geo: {
        lat: "-43.9509",
        lng: "-34.4618",
      },
    },
    phone: "010-692-6593 x09125",
    website: "anastasia.net",
    company: {
      name: "Deckow-Crist",
      catchPhrase: "Proactive didactic contingency",
      bs: "synergize scalable supply-chains",
    },
  },
  {
    id: 3,
    name: "Musfiqur Rahim",
    img: "http://t2.gstatic.com/licensed-image?q=tbn:ANd9GcTfcZjB4G7brLc0WCJTrGZg_zLhZmAvbKaflM7PLyprELSo7Zfgx4Ltn8Oa4S_i",

    salary: 8000,
    battingStyle: " Left-handed",
    currentTeam: "Nagar Goldstar",
    username: "Samantha",
    email: "Nathan@yesenia.net",
    address: {
      street: "Douglas Extension",
      suite: "Suite 847",
      city: "McKenziehaven",
      zipcode: "59590-4157",
      geo: {
        lat: "-68.6102",
        lng: "-47.0653",
      },
    },
    phone: "1-463-123-4447",
    website: "ramiro.info",
    company: {
      name: "Romaguera-Jacobson",
      catchPhrase: "Face to face bifurcated interface",
      bs: "e-enable strategic applications",
    },
  },
  {
    id: 4,
    name: "Mehidy Hasan",
    img: "https://media.gettyimages.com/photos/mehedi-hasan-miraz-of-bangladesh-poses-for-a-picture-during-the-picture-id688905782?s=612x612",

    salary: 4000,
    battingStyle: "Right-handed",
    currentTeam: "Khulna Tigers",
    username: "Karianne",
    email: "Julianne.OConner@kory.org",
    address: {
      street: "Hoeger Mall",
      suite: "Apt. 692",
      city: "South Elvis",
      zipcode: "53919-4257",
      geo: {
        lat: "29.4572",
        lng: "-164.2990",
      },
    },
    phone: "493-170-9623 x156",
    website: "kale.biz",
    company: {
      name: "Robel-Corkery",
      catchPhrase: "Multi-tiered zero tolerance productivity",
      bs: "transition cutting-edge web services",
    },
  },
  {
    id: 5,
    name: "Mustafizur Rahman",
    img: "http://t0.gstatic.com/licensed-image?q=tbn:ANd9GcTl3uN5WsH81o0UU0iP7KS53zDvkZlX4IEsrCChcZJTunDJX_978F-u6Uf5KzJu",

    salary: 10000,
    battingStyle: " Left-handed",
    currentTeam: "Khulna Tigers",
    username: "Kamren",
    email: "Lucio_Hettinger@annie.ca",
    address: {
      street: "Skiles Walks",
      suite: "Suite 351",
      city: "Roscoeview",
      zipcode: "33263",
      geo: {
        lat: "-31.8129",
        lng: "62.5342",
      },
    },
    phone: "(254)954-1289",
    website: "demarco.info",
    company: {
      name: "Keebler LLC",
      catchPhrase: "User-centric fault-tolerant solution",
      bs: "revolutionize end-to-end systems",
    },
  },
  {
    id: 6,
    name: "Mahmudullah",
    img: "http://t3.gstatic.com/licensed-image?q=tbn:ANd9GcQCc4R-JU_z5fPf-0LeFWNDwiF88Ru1_5YiwFM4HC4mN5T8tLNAbtOiF7Y5WggT",

    salary: 9000,
    battingStyle: " Left-handed",
    currentTeam: "Khulna Tigers",
    username: "Leopoldo_Corkery",
    email: "Karley_Dach@jasper.info",
    address: {
      street: "Norberto Crossing",
      suite: "Apt. 950",
      city: "South Christy",
      zipcode: "23505-1337",
      geo: {
        lat: "-71.4197",
        lng: "71.7478",
      },
    },
    phone: "1-477-935-8478 x6430",
    website: "ola.org",
    company: {
      name: "Considine-Lockman",
      catchPhrase: "Synchronised bottom-line interface",
      bs: "e-enable innovative applications",
    },
  },
  {
    id: 7,
    name: "Mosaddek Hossain",
    img: "http://t1.gstatic.com/licensed-image?q=tbn:ANd9GcQQf0Kd21k8QOIANcPSxO3m3KpDd_l4hulrssEVPeMe6KOojSpp7Nrn1iCLDXBN",

    salary: 10000,
    battingStyle: " Right-handed",
    currentTeam: "Sylhet Thunder",
    username: "Elwyn.Skiles",
    email: "Telly.Hoeger@billy.biz",
    address: {
      street: "Rex Trail",
      suite: "Suite 280",
      city: "Howemouth",
      zipcode: "58804-1099",
      geo: {
        lat: "24.8918",
        lng: "21.8984",
      },
    },
    phone: "210.067.6132",
    website: "elvis.io",
    company: {
      name: "Johns Group",
      catchPhrase: "Configurable multimedia task-force",
      bs: "generate enterprise e-tailers",
    },
  },
  {
    id: 8,
    name: "Mahrafe Mortaza",
    img: "http://t3.gstatic.com/licensed-image?q=tbn:ANd9GcTUita0Dueq42YemMDjR5N_-zqVnytWS_Yh2uFatPvHCDq2H0_9XuIT0nRxVN-T",

    salary: 10000,
    battingStyle: " Right-handed",
    currentTeam: "Khulna Tigers",
    username: "Maxime_Nienow",
    email: "Sherwood@rosamond.me",
    address: {
      street: "Ellsworth Summit",
      suite: "Suite 729",
      city: "Aliyaview",
      zipcode: "45169",
      geo: {
        lat: "-14.3990",
        lng: "-120.7677",
      },
    },
    phone: "586.493.6943 x140",
    website: "jacynthe.com",
    company: {
      name: "Abernathy Group",
      catchPhrase: "Implemented secondary concept",
      bs: "e-enable extensible e-tailers",
    },
  },
  {
    id: 9,
    name: "Sabbir Rahman",
    img: "http://t0.gstatic.com/licensed-image?q=tbn:ANd9GcRYFNEY6NVwpX4RR7v3GzV6q5mr_uvz6FUSWyBBlqRvzDcgjOqgKZMtjb22q5S_",

    salary: 10000,
    battingStyle: " Right-handed",
    currentTeam: "Legends of Rupganj",
    username: "Delphine",
    email: "Chaim_McDermott@dana.io",
    address: {
      street: "Dayna Park",
      suite: "Suite 449",
      city: "Bartholomebury",
      zipcode: "76495-3109",
      geo: {
        lat: "24.6463",
        lng: "-168.8889",
      },
    },
    phone: "(775)976-6794 x41206",
    website: "conrad.com",
    company: {
      name: "Yost and Sons",
      catchPhrase: "Switchable contextually-based project",
      bs: "aggregate real-time technologies",
    },
  },
  {
    id: 10,
    name: "Mohammad Mithun",
    img: "https://img1.hscicdn.com/image/upload/f_auto,t_gn_f_345/lsci/db/PICTURES/CMS/319700/319730.png",

    salary: 10000,
    battingStyle: " Left-handed",
    currentTeam: "Khulna Tigers",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    address: {
      street: "Kattie Turnpike",
      suite: "Suite 198",
      city: "Lebsackbury",
      zipcode: "31428-2261",
      geo: {
        lat: "-38.2386",
        lng: "57.2232",
      },
    },
    phone: "024-648-3804",
    website: "ambrose.net",
    company: {
      name: "Hoeger LLC",
      catchPhrase: "Centralized empowering task-force",
      bs: "target end-to-end models",
    },
  },
];

export default playersData;
